# Generated by Django 5.2.17 on 2026-09-28 04:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã chốt')], default='draft', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.supplier')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.fooditem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.receipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Nhập'), ('OUT', 'Xuất'), ('ADJUST', 'Kiểm kê')], max_length=6)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('value_delta', models.DecimalField(decimal_places=2, max_digits=28)),
                ('date', models.DateField(db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.fooditem')),
                ('receipt_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transaction', to='inventory.receiptline')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posted_at__isnull', True), ('status', 'draft')), models.Q(('posted_at__isnull', False), ('status', 'posted')), _connector='OR'), name='receipt_status_posted_at_valid'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'food'), name='receipt_line_unique_food'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__lt', Decimal('100000000000'))), name='receipt_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0), ('unit_price__lt', Decimal('1000000000000'))), name='receipt_line_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'IN')), name='stock_transaction_m3_in_only'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta__gt', 0), ('quantity_delta__lt', Decimal('100000000000'))), name='stock_transaction_m3_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gt', 0), ('unit_cost__lt', Decimal('1000000000000'))), name='stock_transaction_m3_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('value_delta__gte', 0), ('value_delta__lt', Decimal('100000000000000000000000000'))), name='stock_transaction_m3_value_nonnegative'),
        ),
    ]
