# Generated by Django 5.2.17 on 2026-09-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_receipt_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=32)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('snapshot_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('snapshot_version', models.IntegerField()),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('variance', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_items', to='inventory.fooditem')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake')),
            ],
        ),
    ]
