# Generated by Django 5.2.17 on 2026-09-30 02:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_stocktake_inventoryledger_stocktakeitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("date", models.DateField()),
                ("note", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Nháp"), ("posted", "Đã chốt")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="IssueLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="stocktransaction",
            name="stock_transaction_m3_in_only",
        ),
        migrations.RemoveConstraint(
            model_name="stocktransaction",
            name="stock_transaction_m3_qty_positive",
        ),
        migrations.RemoveConstraint(
            model_name="stocktransaction",
            name="stock_transaction_m3_cost_positive",
        ),
        migrations.RemoveConstraint(
            model_name="stocktransaction",
            name="stock_transaction_m3_value_nonnegative",
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="receipt_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_transaction",
                to="inventory.receiptline",
            ),
        ),
        migrations.AddConstraint(
            model_name="fooditem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__gte", 0), ("quantity__lt", Decimal("100000000000"))
                ),
                name="food_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fooditem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("avg_cost__gte", 0), ("avg_cost__lt", Decimal("1000000000000"))
                ),
                name="food_avg_cost_nonnegative",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueline",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issue_lines",
                to="inventory.fooditem",
            ),
        ),
        migrations.AddField(
            model_name="issueline",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory.issue",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="issue_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_transaction",
                to="inventory.issueline",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("issue_line__isnull", True), ("receipt_line__isnull", False)
                    ),
                    models.Q(
                        ("issue_line__isnull", False), ("receipt_line__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="stock_transaction_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("receipt_line__isnull", False), ("type", "IN")),
                    models.Q(("issue_line__isnull", False), ("type", "OUT")),
                    _connector="OR",
                ),
                name="stock_transaction_type_matches_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "IN"), _negated=True),
                    models.Q(
                        ("quantity_delta__gt", 0),
                        ("quantity_delta__lt", Decimal("100000000000")),
                        ("unit_cost__gt", 0),
                        ("unit_cost__lt", Decimal("1000000000000")),
                        ("value_delta__gte", 0),
                        ("value_delta__lt", Decimal("100000000000000000000000000")),
                    ),
                    _connector="OR",
                ),
                name="stock_transaction_in_values",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "OUT"), _negated=True),
                    models.Q(
                        ("quantity_delta__gt", Decimal("-100000000000")),
                        ("quantity_delta__lt", 0),
                        ("unit_cost__gte", 0),
                        ("unit_cost__lt", Decimal("1000000000000")),
                        ("value_delta__gt", Decimal("-100000000000000000000000000")),
                        ("value_delta__lte", 0),
                    ),
                    _connector="OR",
                ),
                name="stock_transaction_out_values",
            ),
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("posted_at__isnull", True), ("status", "draft")),
                    models.Q(("posted_at__isnull", False), ("status", "posted")),
                    _connector="OR",
                ),
                name="issue_status_posted_at_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="issueline",
            constraint=models.UniqueConstraint(
                fields=("issue", "food"), name="issue_line_unique_food"
            ),
        ),
        migrations.AddConstraint(
            model_name="issueline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__gt", 0), ("quantity__lt", Decimal("100000000000"))
                ),
                name="issue_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="issueline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_cost__gte", 0), ("unit_cost__lt", Decimal("1000000000000"))
                ),
                name="issue_line_cost_nonnegative",
            ),
        ),
    ]
