# Generated by Django 5.2.17 on 2026-09-29 09:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stocktake_inventoryledger_stocktakeitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã chốt')], default='draft', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='inventory.fooditem')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.issue')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'food'), name='issue_line_unique_food')],
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.dish')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='inventory.fooditem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dish', 'food'), name='recipe_component_unique_food')],
            },
        ),
    ]
