# Generated by Django 5.2.17 on 2026-09-29 09:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# Sửa khi gộp SF43 (TV1, 30/09/2026): bản gốc của nhánh feat/Nguyen_Dat tạo lại Issue/IssueLine,
# trùng với 0008_issue_contract (SF25) → hai lá migration và bảng bị tạo hai lần, `migrate` lỗi.
# Giữ nguyên TÊN file (để DB đã chạy bản cũ vẫn nhận ra), chỉ bỏ Issue/IssueLine.
# SchoolClass được SF43 mở rộng ở 0012_lunch_counts.


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stocktake_inventoryledger_stocktakeitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.dish')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='inventory.fooditem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dish', 'food'), name='recipe_component_unique_food')],
            },
        ),
    ]
