# Generated by Django 5.2.17 on 2026-09-30 02:20

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_stocktakes(apps, schema_editor):
    """Dữ liệu local cũ: ngày kiểm kê = ngày tạo; phiếu đã chốt dùng updated_at làm posted_at.

    Không tự điền người chốt: dữ liệu cũ không lưu, để NULL thay vì bịa (architecture.md §2).
    """
    StockTake = apps.get_model("inventory", "StockTake")
    for stocktake in StockTake.objects.filter(date__isnull=True):
        stocktake.date = stocktake.created_at.date()
        stocktake.save(update_fields=["date"])
    for stocktake in StockTake.objects.filter(status="posted", posted_at__isnull=True):
        stocktake.posted_at = stocktake.updated_at
        stocktake.save(update_fields=["posted_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_issue_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocktake",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="stocktakeitem",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveConstraint(
            model_name="stocktransaction",
            name="stock_transaction_one_source",
        ),
        migrations.RemoveConstraint(
            model_name="stocktransaction",
            name="stock_transaction_type_matches_source",
        ),
        migrations.AddField(
            model_name="stocktake",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stocktakes_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="posted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stocktakes_posted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="stocktake_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_transaction",
                to="inventory.stocktakeitem",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="status",
            field=models.CharField(
                choices=[("draft", "Nháp"), ("posted", "Đã chốt")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_legacy_stocktakes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="stocktake",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("posted_at__isnull", True), ("status", "draft")),
                    models.Q(("posted_at__isnull", False), ("status", "posted")),
                    _connector="OR",
                ),
                name="stocktake_status_posted_at_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeitem",
            constraint=models.UniqueConstraint(
                fields=("stock_take", "food"), name="stocktake_item_unique_food"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("snapshot_qty__gte", 0),
                    ("snapshot_qty__lt", Decimal("100000000000")),
                ),
                name="stocktake_item_snapshot_qty_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("snapshot_cost__gte", 0),
                    ("snapshot_cost__lt", Decimal("1000000000000")),
                ),
                name="stocktake_item_snapshot_cost_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("counted_qty__isnull", True), ("variance", 0)),
                    models.Q(
                        ("counted_qty__gte", 0),
                        ("counted_qty__isnull", False),
                        ("counted_qty__lt", Decimal("100000000000")),
                        (
                            "variance",
                            django.db.models.expressions.CombinedExpression(
                                models.F("counted_qty"), "-", models.F("snapshot_qty")
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="stocktake_item_variance_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("issue_line__isnull", True),
                        ("receipt_line__isnull", False),
                        ("stocktake_item__isnull", True),
                    ),
                    models.Q(
                        ("issue_line__isnull", False),
                        ("receipt_line__isnull", True),
                        ("stocktake_item__isnull", True),
                    ),
                    models.Q(
                        ("issue_line__isnull", True),
                        ("receipt_line__isnull", True),
                        ("stocktake_item__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="stock_transaction_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("receipt_line__isnull", False), ("type", "IN")),
                    models.Q(("issue_line__isnull", False), ("type", "OUT")),
                    models.Q(("stocktake_item__isnull", False), ("type", "ADJUST")),
                    _connector="OR",
                ),
                name="stock_transaction_type_matches_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "ADJUST"), _negated=True),
                    models.Q(
                        ("unit_cost__gte", 0),
                        ("unit_cost__lt", Decimal("1000000000000")),
                        models.Q(
                            models.Q(
                                ("quantity_delta__gt", 0),
                                ("quantity_delta__lt", Decimal("100000000000")),
                                ("value_delta__gte", 0),
                                (
                                    "value_delta__lt",
                                    Decimal("100000000000000000000000000"),
                                ),
                            ),
                            models.Q(
                                ("quantity_delta__gt", Decimal("-100000000000")),
                                ("quantity_delta__lt", 0),
                                (
                                    "value_delta__gt",
                                    Decimal("-100000000000000000000000000"),
                                ),
                                ("value_delta__lte", 0),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="stock_transaction_adjust_values",
            ),
        ),
    ]
