# Generated by Django 5.2.17 on 2026-09-30 02:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_stocktake_integrity"),
        # Gộp nhánh SF44/SF50 (TV2): bảng SchoolClass đã có từ migration này.
        ("inventory", "0008_dish_schoolclass_issue_issueline_recipecomponent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LunchDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "staff_planned",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "staff_actual",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "planned_confirmed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "actual_confirmed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actual_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lunch_actual_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "planned_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lunch_planned_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LunchDayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("confirm_planned", "Chốt dự kiến"),
                            ("reopen_planned", "Mở lại dự kiến"),
                            ("confirm_actual", "Chốt thực tế"),
                            ("reopen_actual", "Mở lại thực tế"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("reason", models.TextField(blank=True, default="")),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lunch_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lunch_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="inventory.lunchday",
                    ),
                ),
            ],
            options={
                "ordering": ["lunch_day_id", "version", "id"],
            },
        ),
        # SchoolClass đã được tạo ở 0008 (SF44, TV2) với code/name/is_active; SF43 bổ sung phần còn lại.
        migrations.AlterModelOptions(
            name="schoolclass",
            options={"ordering": ["code"]},
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="enrolled",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.CheckConstraint(
                condition=models.Q(("enrolled__gte", 0), ("enrolled__lte", 200)),
                name="school_class_enrolled_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("grade__isnull", True),
                    models.Q(("grade__gte", 1), ("grade__lte", 12)),
                    _connector="OR",
                ),
                name="school_class_grade_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="school_class_code_not_empty",
            ),
        ),
        migrations.CreateModel(
            name="ClassMealCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_snapshot", models.PositiveSmallIntegerField()),
                ("planned", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("actual", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "lunch_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_counts",
                        to="inventory.lunchday",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_counts",
                        to="inventory.schoolclass",
                    ),
                ),
            ],
            options={
                "ordering": ["lunch_day_id", "school_class_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="lunchday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("staff_planned__isnull", True),
                    ("staff_planned__lte", 1000),
                    _connector="OR",
                ),
                name="lunch_day_staff_planned_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="lunchday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("staff_actual__isnull", True),
                    ("staff_actual__lte", 1000),
                    _connector="OR",
                ),
                name="lunch_day_staff_actual_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="lunchday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("planned_confirmed_at__isnull", True),
                        ("planned_confirmed_by__isnull", True),
                    ),
                    models.Q(
                        ("planned_confirmed_at__isnull", False),
                        ("planned_confirmed_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="lunch_day_planned_confirm_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="lunchday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actual_confirmed_at__isnull", True),
                        ("actual_confirmed_by__isnull", True),
                    ),
                    models.Q(
                        ("actual_confirmed_at__isnull", False),
                        ("actual_confirmed_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="lunch_day_actual_confirm_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="lunchday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_confirmed_at__isnull", True),
                    ("planned_confirmed_at__isnull", False),
                    _connector="OR",
                ),
                name="lunch_day_actual_after_planned",
            ),
        ),
        migrations.AddConstraint(
            model_name="lunchday",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="lunch_day_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="lunchdayevent",
            constraint=models.UniqueConstraint(
                fields=("lunch_day", "version"), name="lunch_day_event_unique_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="lunchdayevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("action__in", ["confirm_planned", "confirm_actual"]),
                    models.Q(("reason__regex", "^\\s*$"), _negated=True),
                    _connector="OR",
                ),
                name="lunch_day_event_reopen_needs_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="classmealcount",
            constraint=models.UniqueConstraint(
                fields=("lunch_day", "school_class"), name="class_meal_count_unique_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="classmealcount",
            constraint=models.CheckConstraint(
                condition=models.Q(("enrolled_snapshot__lte", 200)),
                name="class_meal_count_snapshot_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="classmealcount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planned__isnull", True),
                    ("planned__lte", models.F("enrolled_snapshot")),
                    _connector="OR",
                ),
                name="class_meal_count_planned_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="classmealcount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual__isnull", True),
                    ("actual__lte", models.F("enrolled_snapshot")),
                    _connector="OR",
                ),
                name="class_meal_count_actual_valid",
            ),
        ),
    ]
