# Generated by Django 5.2.17 on 2026-10-01 04:17
"""BE-02 (PR1 security): vai trò, khóa đăng nhập sai, nhật ký thao tác.

- Group "manager" (Quản lý) và "principal" (Hiệu trưởng); tạo idempotent, lùi migration không xóa
  group vì có thể đã gán người dùng.
- LoginThrottle: bộ đếm đăng nhập sai (logic ở BE-10).
- AuditLog: chỉ thêm. Trigger chặn UPDATE/DELETE từng dòng; TRUNCATE (flush khi test, dọn có chủ đích
  của quản trị DB) không đi qua trigger dòng.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ROLE_GROUPS = ("manager", "principal")


def create_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ROLE_GROUPS:
        Group.objects.using(schema_editor.connection.alias).get_or_create(name=name)


FORWARD_SQL = """
CREATE FUNCTION be02_audit_log_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Audit log is append-only'
        USING ERRCODE = '23514', CONSTRAINT = 'audit_log_append_only';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER be02_audit_log_append_only BEFORE UPDATE OR DELETE ON inventory_auditlog
FOR EACH ROW EXECUTE FUNCTION be02_audit_log_append_only();
"""

REVERSE_SQL = """
DROP TRIGGER be02_audit_log_append_only ON inventory_auditlog;
DROP FUNCTION be02_audit_log_append_only();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_lunch_integrity'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_role_groups, migrations.RunPython.noop),
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('user', 'Tên đăng nhập'), ('ip', 'Địa chỉ IP')], max_length=10)),
                ('key_hash', models.CharField(max_length=64)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash'), name='login_throttle_unique_key'), models.CheckConstraint(condition=models.Q(('scope__in', ['user', 'ip'])), name='login_throttle_scope_valid'), models.CheckConstraint(condition=models.Q(('key_hash__regex', '^[0-9a-f]{64}$')), name='login_throttle_key_hash_hex')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(max_length=40)),
                ('entity_type', models.CharField(blank=True, default='', max_length=40)),
                ('entity_id', models.CharField(blank=True, default='', max_length=40)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='audit_log_created_idx'), models.Index(fields=['actor', 'created_at'], name='audit_log_actor_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action', ''), _negated=True), name='audit_log_action_not_empty')],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
