"""BE-03 / SF49: thực đơn cố định theo thứ, ngày nghỉ, bản chụp theo ngày; công thức 6 số lẻ."""
# Generated by Django 5.2.17 on 2026-10-01 04:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def refuse_zero_quantities(apps, schema_editor):
    """ISSUE-003: dòng công thức = 0 (do làm tròn 3 số lẻ trước đây) phải được người phụ trách nhập lại,
    không tự đoán. Có dòng như vậy thì dừng migration và in danh sách."""
    RecipeComponent = apps.get_model("inventory", "RecipeComponent")
    bad = list(
        RecipeComponent.objects.using(schema_editor.connection.alias)
        .filter(quantity__lte=0).values_list("dish__code", "food__code")
    )
    if bad:
        listing = ", ".join(f"{dish}/{food}" for dish, food in bad)
        raise RuntimeError(
            "Có dòng công thức định lượng ≤ 0 (ISSUE-003): " + listing
            + ". Sửa hoặc xóa các dòng này trong /admin rồi chạy lại migrate."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_roles_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(refuse_zero_quantities, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DayMenuSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MenuVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(unique=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='MenuVersionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['version_id', 'weekday', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='recipecomponent',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__lt', Decimal('100000000'))), name='recipe_component_quantity_positive'),
        ),
        migrations.AddField(
            model_name='menuversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daymenusnapshot',
            name='menu_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='inventory.menuversion'),
        ),
        migrations.AddField(
            model_name='menuversionitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='inventory.dish'),
        ),
        migrations.AddField(
            model_name='menuversionitem',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.menuversion'),
        ),
        migrations.AddField(
            model_name='schoolholiday',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holidays_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='menuversionitem',
            constraint=models.UniqueConstraint(fields=('version', 'weekday', 'dish'), name='menu_item_unique_dish'),
        ),
        migrations.AddConstraint(
            model_name='menuversionitem',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 4)), name='menu_item_weekday_valid'),
        ),
        migrations.AddConstraint(
            model_name='schoolholiday',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='school_holiday_name_not_empty'),
        ),
    ]
