# Generated by Django 5.2.17 on 2026-10-01 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_menu_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('email_hash', models.CharField(max_length=64)),
                ('student_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('dry_run', 'Chế độ thử'), ('sent', 'Đã gửi'), ('failed', 'Lỗi'), ('skipped', 'Bỏ qua'), ('pending', 'Đang gửi')], max_length=10)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('date', 'email_hash'), name='notification_unique_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='inventory.schoolclass')),
            ],
            options={
                'ordering': ['school_class_id', 'full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_encrypted', models.TextField()),
                ('email_hash', models.CharField(db_index=True, max_length=64)),
                ('email_hint', models.CharField(max_length=80)),
                ('consent_at', models.DateTimeField()),
                ('consent_note', models.CharField(blank=True, default='', max_length=200)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_contacts_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='inventory.student')),
            ],
            options={
                'ordering': ['student_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('full_name', ''), _negated=True), name='student_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='parentcontact',
            constraint=models.UniqueConstraint(fields=('student', 'email_hash'), name='parent_contact_unique_email'),
        ),
        migrations.AddConstraint(
            model_name='parentcontact',
            constraint=models.CheckConstraint(condition=models.Q(('email_hash__regex', '^[0-9a-f]{64}$')), name='parent_contact_hash_hex'),
        ),
        migrations.AddConstraint(
            model_name='parentcontact',
            constraint=models.CheckConstraint(condition=models.Q(('email_encrypted__contains', '@'), _negated=True), name='parent_contact_not_plaintext'),
        ),
    ]
