# Generated by Django 5.2.17 on 2026-10-01 05:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_students_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='lunch_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.lunchday'),
        ),
        migrations.CreateModel(
            name='DemandRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Bản tính'), ('approved', 'Đã duyệt'), ('stale', 'Lỗi thời')], default='draft', max_length=10)),
                ('servings', models.PositiveIntegerField()),
                ('lunch_day_version', models.PositiveIntegerField()),
                ('menu_items', models.JSONField(default=list)),
                ('stale_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_revisions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('lunch_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_revisions', to='inventory.lunchday')),
                ('menu_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_revisions', to='inventory.menuversion')),
            ],
            options={
                'ordering': ['lunch_day_id', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='DemandLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reserve_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reserve_reason', models.CharField(blank=True, default='', max_length=255)),
                ('from_stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('from_pending_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('to_buy_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_lines', to='inventory.fooditem')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.demandrevision')),
            ],
            options={
                'ordering': ['revision_id', 'food_id'],
            },
        ),
        migrations.CreateModel(
            name='LunchDayClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('summary', models.JSONField(default=dict)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.CharField(blank=True, default='', max_length=255)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lunch_days_closed', to=settings.AUTH_USER_MODEL)),
                ('lunch_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closes', to='inventory.lunchday')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lunch_days_reopened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lunch_day_id', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('approved', 'Đã duyệt'), ('sent', 'Đã gửi NCC'), ('closed', 'Đã đóng'), ('cancelled', 'Đã hủy')], default='draft', max_length=10)),
                ('expected_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('close_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('demand_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.demandrevision')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_received', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_price_est', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='inventory.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['order_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='receiptline',
            name='po_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.purchaseorderline'),
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('stock', 'Tồn kho'), ('po_line', 'Đơn đang chờ')], max_length=10)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('reserved', 'Đang giữ'), ('consumed', 'Đã dùng'), ('released', 'Đã bỏ giữ')], default='reserved', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.demandline')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.fooditem')),
                ('lunch_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.lunchday')),
                ('po_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.purchaseorderline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='demandrevision',
            constraint=models.UniqueConstraint(fields=('lunch_day', 'revision'), name='demand_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='demandrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('lunch_day',), name='demand_one_approved_per_day'),
        ),
        migrations.AddConstraint(
            model_name='demandrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('status', 'approved')), models.Q(('status', 'approved'), _negated=True), _connector='OR'), name='demand_approved_has_actor'),
        ),
        migrations.AddConstraint(
            model_name='demandline',
            constraint=models.UniqueConstraint(fields=('revision', 'food'), name='demand_line_unique_food'),
        ),
        migrations.AddConstraint(
            model_name='demandline',
            constraint=models.CheckConstraint(condition=models.Q(('from_pending_qty__gte', 0), ('from_stock_qty__gte', 0), ('required_qty__gte', 0), ('required_qty__lt', Decimal('100000000000')), ('reserve_qty__gte', 0), ('reserve_qty__lt', Decimal('100000000000')), ('to_buy_qty__gte', 0)), name='demand_line_quantities_valid'),
        ),
        migrations.AddConstraint(
            model_name='demandline',
            constraint=models.CheckConstraint(condition=models.Q(('reserve_qty', 0), models.Q(('reserve_reason', ''), _negated=True), _connector='OR'), name='demand_line_reserve_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='lunchdayclose',
            constraint=models.UniqueConstraint(condition=models.Q(('reopened_at__isnull', True)), fields=('lunch_day',), name='lunch_day_one_active_close'),
        ),
        migrations.AddConstraint(
            model_name='lunchdayclose',
            constraint=models.CheckConstraint(condition=models.Q(('reopened_at__isnull', True), models.Q(('reopen_reason', ''), _negated=True), _connector='OR'), name='lunch_day_reopen_close_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='purchase_order_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['closed', 'cancelled']), _negated=True), models.Q(('close_reason', ''), _negated=True), _connector='OR'), name='purchase_order_close_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'food'), name='po_line_unique_food'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_ordered__gt', 0), ('qty_ordered__lt', Decimal('100000000000'))), name='po_line_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_received__gte', 0), ('qty_received__lte', models.F('qty_ordered'))), name='po_line_received_not_over'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['food', 'status', 'source'], name='allocation_food_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0), ('qty__lt', Decimal('100000000000'))), name='allocation_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('po_line__isnull', True), ('source', 'stock')), models.Q(('po_line__isnull', False), ('source', 'po_line')), _connector='OR'), name='allocation_source_matches_po_line'),
        ),
    ]
