# Generated by Django 5.2.17 on 2026-10-01 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_demand_purchase_day_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=200, upload_to='meal_photos/')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lunch_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='inventory.lunchday')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lunch_day_id', 'id'],
            },
        ),
    ]
