# Generated by Django 5.2.17 on 2026-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_meal_photo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="menuversionitem",
            name="menu_item_weekday_valid",
        ),
        migrations.AddConstraint(
            model_name="menuversionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 5)),
                name="menu_item_weekday_valid",
            ),
        ),
    ]
