"""BE-01 / ISSUE-001: nâng cấp DB đã migrate ở f00048d.

Ca đầu-cuối dựng DB legacy thật trong một database PostgreSQL tạm: migrate code hiện tại tới
0008_dish… (bản mới không có Issue) rồi chạy đúng DDL Issue/IssueLine mà 0008 bản f00048d sinh ra
(lấy từ `sqlmigrate` chạy trên checkout f00048d). Lệnh chạy bằng subprocess như người dùng thật.
"""

import os
import subprocess
import sys
import uuid
from io import StringIO

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import CommandError
from django.db import connection
from django.test import SimpleTestCase, TestCase, TransactionTestCase

from .legacy_db import (
    BLOCKED,
    CLEAN,
    CONTRACT_MIGRATION,
    LEGACY_COLUMNS,
    LEGACY_EMPTY,
    LEGACY_HAS_DATA,
    LEGACY_MIGRATION,
    UNKNOWN,
    UP_TO_DATE,
    Facts,
    collect_facts,
    diagnose,
)

# `sqlmigrate inventory 0008_dish_schoolclass_issue_issueline_recipecomponent` tại f00048d, phần Issue.
F00048D_ISSUE_DDL = """
CREATE TABLE "inventory_issue" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "code" varchar(32) NOT NULL UNIQUE, "date" date NOT NULL, "note" text NOT NULL, "status" varchar(10) NOT NULL, "posted_at" timestamp with time zone NULL, "created_by_id" integer NOT NULL);
CREATE TABLE "inventory_issueline" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" numeric(14, 3) NOT NULL, "unit_cost" numeric(14, 2) NOT NULL, "food_id" bigint NOT NULL, "issue_id" bigint NOT NULL, CONSTRAINT "issue_line_unique_food" UNIQUE ("issue_id", "food_id"));
ALTER TABLE "inventory_issue" ADD CONSTRAINT "inventory_issue_created_by_id_825c0135_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventory_issue_code_31118b5f_like" ON "inventory_issue" ("code" varchar_pattern_ops);
CREATE INDEX "inventory_issue_created_by_id_825c0135" ON "inventory_issue" ("created_by_id");
ALTER TABLE "inventory_issueline" ADD CONSTRAINT "inventory_issueline_food_id_e3f21765_fk_inventory_fooditem_id" FOREIGN KEY ("food_id") REFERENCES "inventory_fooditem" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventory_issueline" ADD CONSTRAINT "inventory_issueline_issue_id_0ccc691b_fk_inventory_issue_id" FOREIGN KEY ("issue_id") REFERENCES "inventory_issue" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventory_issueline_food_id_e3f21765" ON "inventory_issueline" ("food_id");
CREATE INDEX "inventory_issueline_issue_id_0ccc691b" ON "inventory_issueline" ("issue_id");
"""

OLD_TABLES = {t: (0, cols) for t, cols in LEGACY_COLUMNS.items()}
APPLIED_OLD = frozenset({"0007_stocktake_inventoryledger_stocktakeitem", LEGACY_MIGRATION})


class DiagnoseTests(SimpleTestCase):
    def test_states(self):
        cases = [
            (Facts(APPLIED_OLD | {CONTRACT_MIGRATION}, dict(OLD_TABLES), ()), UP_TO_DATE),
            (Facts(APPLIED_OLD, {}, ()), CLEAN),
            (Facts(frozenset(), {}, ()), CLEAN),
            (Facts(APPLIED_OLD, dict(OLD_TABLES), ()), LEGACY_EMPTY),
            (Facts(APPLIED_OLD, {**OLD_TABLES, "inventory_issue": (3, LEGACY_COLUMNS["inventory_issue"])}, ()), LEGACY_HAS_DATA),
            (Facts(APPLIED_OLD, dict(OLD_TABLES), ("inventory_x.fk_issue",)), BLOCKED),
            (Facts(frozenset({"0007_stocktake_inventoryledger_stocktakeitem"}), dict(OLD_TABLES), ()), UNKNOWN),
            (Facts(APPLIED_OLD, {**OLD_TABLES, "inventory_issue": (0, frozenset({"id", "code"}))}, ()), UNKNOWN),
        ]
        for facts, expected in cases:
            with self.subTest(expected=expected, facts=facts):
                self.assertEqual(diagnose(facts).state, expected)

    def test_data_message_reports_counts(self):
        facts = Facts(APPLIED_OLD, {**OLD_TABLES, "inventory_issueline": (5, LEGACY_COLUMNS["inventory_issueline"])}, ())
        self.assertIn("inventory_issueline=5 dòng", diagnose(facts).message)


class CurrentDatabaseTests(TestCase):
    def test_fully_migrated_database_needs_nothing(self):
        self.assertEqual(diagnose(collect_facts(connection)).state, UP_TO_DATE)
        out = StringIO()
        call_command("sf_legacy_db_check", "--apply", stdout=out)
        self.assertIn("up_to_date", out.getvalue())
        self.assertIn("inventory_issue", connection.introspection.table_names())


class LegacyUpgradeEndToEndTests(TransactionTestCase):
    """Chạy migrate thật hai lần trong DB tạm: chậm hơn các test khác (~30 giây)."""

    def setUp(self):
        self.db_name = f"sf_legacy_{uuid.uuid4().hex[:8]}"
        with connection.cursor() as cursor:
            cursor.execute(f'CREATE DATABASE "{self.db_name}"')
        cfg = connection.settings_dict
        self.env = {
            **os.environ,
            "DB_NAME": self.db_name,
            "DB_HOST": str(cfg["HOST"]),
            "DB_PORT": str(cfg["PORT"]),
            "DB_USER": str(cfg["USER"]),
            "DB_PASSWORD": str(cfg["PASSWORD"]),
            "PYTHONIOENCODING": "utf-8",
        }
        self.env.pop("DATABASE_URL", None)
        self.manage("migrate", "inventory", LEGACY_MIGRATION, "--noinput")
        self.sql(F00048D_ISSUE_DDL)

    def tearDown(self):
        with connection.cursor() as cursor:
            cursor.execute(f'DROP DATABASE IF EXISTS "{self.db_name}" WITH (FORCE)')

    def manage(self, *args, expect=0):
        result = subprocess.run(
            [sys.executable, str(settings.BASE_DIR / "manage.py"), *args],
            env=self.env, capture_output=True, text=True, encoding="utf-8", timeout=300,
        )
        self.assertEqual(result.returncode, expect, msg=f"{args}\n{result.stdout}\n{result.stderr}")
        return result.stdout + result.stderr

    def _connect(self):
        import psycopg

        cfg = connection.settings_dict
        return psycopg.connect(
            host=cfg["HOST"], port=cfg["PORT"], user=cfg["USER"], password=cfg["PASSWORD"],
            dbname=self.db_name, autocommit=True,
        )

    def sql(self, statements):
        with self._connect() as conn:
            conn.execute(statements)

    def scalar(self, query):
        with self._connect() as conn:
            return conn.execute(query).fetchone()[0]

    def test_reproduces_issue_then_upgrades_empty_legacy_db(self):
        out = self.manage("migrate", "--noinput", expect=1)
        self.assertIn('relation "inventory_issue" already exists', out)

        self.assertIn(LEGACY_EMPTY, self.manage("sf_legacy_db_check"))
        self.assertIn("Đã xóa bảng rỗng inventory_issue", self.manage("sf_legacy_db_check", "--apply"))
        self.manage("migrate", "--noinput")
        self.assertIn(UP_TO_DATE, self.manage("sf_legacy_db_check"))
        self.manage("sf31_ledger_audit", "--strict")
        self.manage("makemigrations", "--check", "--dry-run")
        triggers = self.scalar("SELECT count(*) FROM pg_trigger WHERE NOT tgisinternal")
        with connection.cursor() as cursor:
            cursor.execute("SELECT count(*) FROM pg_trigger WHERE NOT tgisinternal")
            self.assertEqual(triggers, cursor.fetchone()[0])

    def test_refuses_legacy_tables_with_data(self):
        self.sql(
            "INSERT INTO auth_user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) "
            "VALUES ('!', now(), false, 'legacy', '', '', '', false, true, now());"
            "INSERT INTO inventory_issue (code, date, note, status, created_by_id) "
            "SELECT 'PX-CU', '2026-09-29', '', 'draft', id FROM auth_user WHERE username = 'legacy';"
        )
        out = self.manage("sf_legacy_db_check", "--apply", expect=1)
        self.assertIn(LEGACY_HAS_DATA, out)
        self.assertIn("inventory_issue=1 dòng", out)
        self.assertEqual(self.scalar("SELECT count(*) FROM inventory_issue"), 1)


class CommandRefusalTests(TestCase):
    def test_command_error_for_states_needing_a_person(self):
        from unittest import mock

        from .management.commands import sf_legacy_db_check as cmd

        facts = Facts(APPLIED_OLD, {**OLD_TABLES, "inventory_issue": (2, LEGACY_COLUMNS["inventory_issue"])}, ())
        with mock.patch.object(cmd, "collect_facts", return_value=facts), self.assertRaises(CommandError):
            call_command("sf_legacy_db_check", stdout=StringIO())
